inherit_from: .rubocop_todo.yml

LineLength:
  Max: 105

Encoding:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

EndAlignment:
  AlignWith: variable
