LineLength:
  # just a really annoying check, especially when logging
  Enabled: false

ClassLength:
  Max: 150

Encoding:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Exclude:
    - 'lib/sqeduler/version.rb'

EndAlignment:
  AlignWith: variable

Metrics/MethodLength:
  Max: 20

